version: "3"

services:

  web:
    container_name: pyeditorial
    image: pyeditorial
    build:
      context: .
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
    depends_on:
      - postgre_db
    networks:
      - nets

  nginx:
    container_name: nginx_pyeditorial
    image: nginx_pyeditorial
    build:
      context: nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - nets

  postgre_db:
    container_name: postgre_db
    image: postgres
    environment:
      POSTGRES_DB: pyeditorial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
    ports:
        - "5432:5432"
    networks:
      - nets
  
networks:
  nets:
